//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BuchShop.Geschaeftslogik.Domaenenobjekte
{
    public class Adresse
	{
		public virtual string Strasse
		{
			get;
			set;
		}

		public virtual int Postleitzahl
		{
			get;
			set;
		}

		public virtual int Hausnummer
		{
			get;
			set;
		}

	}
}

