//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BuchShop.Geschaeftslogik.Domaenenobjekte
{
    using System.ComponentModel.DataAnnotations;

    public partial class Artikel
	{
		public virtual string Titel
		{
			get;
			set;
		}
        
        public virtual decimal Preis
		{
			get;
			set;
		}

		public virtual int Anzahl
		{
			get;
			set;
		}

		public virtual int Artikelnummer
		{
			get;
			set;
		}

		public virtual bool Lieferbar
		{
			get;
			set;
		}

	}
}

