//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BuchShop.Geschaeftslogik.Domaenenobjekte
{
    public class Buch : Artikel
	{
		public virtual string Autor
		{
			get;
			set;
		}

		public virtual string Zusammenfassung
		{
			get;
			set;
		}

	}
}

