//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BuchShop.Geschaeftslogik.Domaenenobjekte
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class Kunde : Nutzer
	{
		public virtual int Treuepunkte
		{
			get;
			set;
		}

		public virtual Kundenstatus Status
		{
			get;
			set;
		}

		public virtual Adresse Rechnungsadresse
		{
			get;
			set;
		}

		public virtual IEnumerable<Adresse> Lieferadresse
		{
			get;
			set;
		}

	}
}

