//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BuchShop.Geschaeftslogik.Domaenenobjekte
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Mitarbeiter : Nutzer
	{
		public virtual string Telefonnummer
		{
			get;
			set;
		}

	}
}

