//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace BuchShop.Geschaeftslogik.Domaenenobjekte
{
    public class Nutzer
    {
        [Required]
        [Display(Name = "E-Mail")]
        [EmailAddress(ErrorMessage = "Ungültige E-Mail Adressse")]
        public virtual string Email
		{
			get;
			set;
		}

        [Required]
        public virtual string Passwort
		{
			get;
			set;
		}

		public virtual int Identifikationsnummer
		{
			get;
			set;
		}

		public virtual string Name
		{
			get;
			set;
		}

	}
}

