//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BuchShop.Geschaeftslogik.Domaenenobjekte
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class Warenkorb
	{
		public virtual string Rabattcode
		{
			get;
			set;
		}

		private static decimal versandkosten = 4;

		public virtual Kunde Kunde
		{
			get;
			set;
		}

		public virtual IEnumerable<Artikel> Artikel
		{
			get;
			set;
		}

	}
}

